export const CREATE_SNIPPET_LOADING = "CREATE_SNIPPET_LOADING ";
export const CREATE_SNIPPET_SUCCESS = "CREATE_SNIPPET_SUCCESS ";
export const CREATE_SNIPPET_FAILURE = "CREATE_SNIPPET_FAILURE ";

export const GET_ALL_SNIPPET_LOADING = "GET_ALL_SNIPPET_LOADING";
export const GET_ALL_SNIPPET_SUCCESS = "GET_ALL_SNIPPET_SUCCESS";
export const GET_ALL_SNIPPET_FAILURE = "GET_ALL_SNIPPET_FAILURE";
